# Generated by Django 5.1 on 2024-09-13 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('subscriptions', models.CharField(max_length=200)),
                ('cardSaved', models.BooleanField(default=False)),
                ('addressSaved', models.BooleanField(default=False)),
                ('experienceLink', models.URLField()),
                ('testAccountOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
