# Generated by Django 5.1 on 2024-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAccountExperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testaccount',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='testaccount',
            name='language',
            field=models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English'), ('Swedish', 'Swedish'), ('Vietnamese', 'Vietnamese'), ('Malay', 'Malay'), ('Danish', 'Danish'), ('Arabic', 'Arabic'), ('Turkish', 'Turkish'), ('French', 'French'), ('Dutch', 'Dutch'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Luxembourgish', 'Luxembourgish'), ('Japanese', 'Japanese'), ('Indonesian', 'Indonesian'), ('Guaraní', 'Guaraní'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Polish', 'Polish'), ('German', 'German'), ('Romanian', 'Romanian'), ('Italian', 'Italian'), ('Tagalog', 'Tagalog'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Norwegian', 'Norwegian')], max_length=200),
        ),
        migrations.AlterField(
            model_name='testaccount',
            name='location',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Barbados', 'Barbados'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Denmark', 'Denmark'), ('France', 'France'), ('Germany', 'Germany'), ('Hungary', 'Hungary'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Kenya', 'Kenya'), ('Luxembourg', 'Luxembourg'), ('Malaysia', 'Malaysia'), ('Mexico', 'Mexico'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nigeria', 'Nigeria'), ('Norway', 'Norway'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Paraguay', 'Paraguay'), ('Romania', 'Romania'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Vietnam', 'Vietnam'), ('South Africa', 'South Africa')], max_length=200),
        ),
    ]
